### ISSUE TITLE
关于github推送频率

### ISSUE THREAD

**Issue by TongYuZhe** [nsi-stlab/algvisualizer#3]
现在制定的计划中github的推送频率为一天一次，调整为每做完一个功能后推送一次是不是更合适一些？

**Comment by DaweiXia** [comment]
嗯，可以

在 2019-03-06 11:10:11，"TongYuZhe" <notifications@github.com> 写道：


现在制定的计划中github的推送频率为一天一次，调整为每做完一个功能后推送一次是不是更合适一些？
